FROM node:20.12.0-alpine3.19

WORKDIR /webhook/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps/bank-webhook ./apps/bank-webhook
COPY packages ./packages

RUN npm install
RUN cd packages/db && npx prisma generate

RUN npm run build

EXPOSE 3003

CMD ["npm", "run", "start-webhook"]
